# Generated by Django 2.0.7 on 2018-07-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_entrada_alamcen_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='proovedor',
            name='empresa',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
