# Generated by Django 2.0.7 on 2018-07-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20180726_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='alamcen_entrada',
            new_name='alamacen_entrada',
        ),
    ]
